name: v2xset_pointpillar_single_w_uncertainty

root_dir: "my_v2xset/train"
validate_dir: "my_v2xset/validate"
test_dir: "my_v2xset/test"

noise_setting:
  add_noise: False
  # args: 
  #   pos_std: 0.2
  #   rot_std: 0.2
  #   pos_mean: 0
  #   rot_mean: 0

exp_name: ""
num_sweep_frames: &past_k 1 # 历史帧使用三帧 fixed
time_delay: 0
binomial_n: 10
binomial_p: 0
is_generate_gt_flow: False # 生成GT Flow 用于去训练flow estimate
is_no_shift: True
viz_bbx_flag: &viz_bbx_flag False
is_single_pre_trained:
  pre_train_flag: false
  # pre_train_fix: true 
  # pre_train_path: /GPFS/rhome/yifanlu/workspace/OpenCOODv2/opencood/logs/point_pillar_late_fusion_channel256_2022_12_14_21_52_25
  # pre_train_epoch: 24

is_same_sample_interval: False # 间隔300ms满足实验条件

comm_range: 70

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 8
  epoches: 30
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 5
  supervise_single_flag: False

fusion:
  core_method: 'IntermediateFusionDatasetV2XSETFlowXYJNew' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset, IntermediateFusionDatasetMultisweep supported
  args:
    proj_first: false
    clip_pc: false

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  past_k: *past_k
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 16000
    max_voxel_test: 40000
  # lidar range for each individual cav. Format: xyzxyz minmax
  cav_lidar_range: &cav_lidar [-70.4, -40, -3, 70.4, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2 # 特征跨度为2个像素点，原本原图范围为200， 704
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

# model related
model:
  core_method: point_pillar_single_uncertainty
  
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: false
    design_mode: 0 # 设计模式定为5
    num_sweep_frames: *past_k
    viz_bbx_flag: *viz_bbx_flag

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      resnet: true
      layer_nums: &layer_nums [3, 4, 5]
      layer_strides: [2, 2, 2]
      num_filters: &num_filters [128, 256, 512]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0
      voxel_size: *voxel_size
      
    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3    

    uncertainty_dim: &uncertainty_dim 3
    re_parameterization: True # 控制是否使用重参数化来衡量分类的数据不确定性
    mc_dropout:
      dropout_rate: 0.1
      inference_stage: false
      inference_num: 10

    rain_model: # fusion_args:
      voxel_size: *voxel_size
      downsample_rate: 1
      in_channels: 256
      n_head: 8
      dropout_rate: 0
      only_attention: true
      communication:
        round: 1
        thre: 0.01
        gaussian_smooth:
          k_size: 5
          c_sigma: 1.0
      agg_operator:
        mode: 'MAX' # MAX, Transformer, ATTEN
        feature_dim: 256
        # mode: 'Transformer'
        # n_head: 8
        # with_spe: true
        # with_scm: true

      multi_scale: true
      layer_nums: *layer_nums
      num_filters: *num_filters
    dir_args: *dir_args


loss:
  core_method: point_pillar_uncertainty_loss
  args:
    cls_weight: 1.0
    reg: 2.0
    kl_weight: 0.25

    dir_args: 
      dir_weight: 0.2
      args: *dir_args
      anchor_yaw: *anchor_yaw

    kl_args:
      angle_weight: 0.5
      uncertainty_dim: *uncertainty_dim
      xy_loss_type: l2
      angle_loss_type: von
      lambda_V: 0.01
      s0: 1
      limit_period: True

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 20]

