name: opv2v_cobevflow_w_uncertainty_HybridFusion_0ms_retry

root_dir: "my_opv2v/train"
validate_dir: "my_opv2v/validate"
test_dir: "my_opv2v/test"

noise_setting:
  add_noise: False
  # args: 
  #   pos_std: 0.2
  #   rot_std: 0.2
  #   pos_mean: 0
  #   rot_mean: 0

exp_name: ""
dataset: "opv2v"
num_sweep_frames: &past_k 2 # 历史帧使用三帧 fixed
time_delay: 0
binomial_n: 10
binomial_p: 0
with_history_frames: true
# is_finetune: true

is_generate_gt_flow: False # 生成GT Flow 用于去训练flow estimate
is_no_shift: True
viz_bbx_flag: &viz_bbx_flag False
is_single_pre_trained:
  pre_train_flag: True
  pre_train_fix: True 
  # pre_train_path: /GPFS/rhome/yifanlu/workspace/OpenCOODv2/opencood/logs/point_pillar_late_fusion_channel256_2022_12_14_21_52_25
  # pre_train_path: /public/home/lilingzhi/xyj/logs/logs/v2xset_pointpillar_single_2024_05_09_15_06_47
  # pre_train_path: /public/home/lilingzhi/xyj/CoAlign/opencood/logs/opv2v_point_pillar_uncertainty_late_fusion_2024_05_24_22_46_34
  # pre_train_path: /public/home/lilingzhi/xyj/logs/logs/v2xset_pointpillar_single_w_uncertainty_2024_05_29_23_32_46
  # pre_train_path: /public/home/lilingzhi/xyj/CoAlign/opencood/logs/opv2v_point_pillar_uncertainty_late_fusion_2024_06_06_15_51_17
  pre_train_path: /public/home/lilingzhi/xyj/CoAlign/opencood/logs/opv2v_point_pillar_uncertainty_late_fusion_2024_07_14_00_21_38
  pre_train_epoch: 56

is_same_sample_interval: False # 间隔300ms满足实验条件

comm_range: 70

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 4
  epoches: &epoches 60
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 5
  supervise_single_flag: False

fusion:
  core_method: 'IntermediateFusionDatasetV2XSETFlowXYJNew' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset, IntermediateFusionDatasetMultisweep supported
  args:
    proj_first: false
    clip_pc: false

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  past_k: *past_k
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav. Format: xyzxyz minmax
  cav_lidar_range: &cav_lidar [-140.8, -40, -3, 140.8, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2 # 特征跨度为2个像素点，原本原图范围为200， 704
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

# model related
model:
  core_method: point_pillar_cobevflow_w_uncertainty
  
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: True
    design_mode: 0 # 设计模式定为5
    num_sweep_frames: *past_k
    viz_bbx_flag: *viz_bbx_flag
    use_uncertainty_guide: True

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      resnet: true
      use_dropout: true
      dropout_enable: true # 这个会使得单车在train以及test的时候dropout都开启 协同训练的时候用于MC Dropout
      layer_nums: &layer_nums [3, 4, 5]
      layer_strides: [2, 2, 2]
      num_filters: &num_filters [128, 256, 512]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0
      voxel_size: *voxel_size

    fuse_bev_backbone:
      resnet: true
      use_dropout: true # fused部分是否开启dropout 开启后在验证以及测试的时候不会开启
      layer_nums: *layer_nums
      layer_strides: [2, 2, 2]
      num_filters: *num_filters
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0
      voxel_size: *voxel_size

    shrink_header:
      use_atten: true
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3    
    
    rain_model: # fusion_args:
      voxel_size: *voxel_size
      downsample_rate: 1
      in_channels: 256
      n_head: 8
      dropout_rate: 0
      only_attention: true
      communication:
        round: 1
        thre: 0.01
        gaussian_smooth:
          k_size: 5
          c_sigma: 1.0
      agg_operator:
        mode: 'HybridFusion' # MAX, Transformer, ATTEN
        feature_dim: 256
        # mode: 'Transformer'
        # n_head: 8
        # with_spe: true
        # with_scm: true

      multi_scale: true
      layer_nums: *layer_nums
      num_filters: *num_filters
    dir_args: *dir_args

    uncertainty_dim: &uncertainty_dim 3
    re_parameterization: true
    mc_dropout: # 单车MC Dropout
      dropout_rate: 0.1
      inference_stage: true
      inference_num: 10

      tp_score_mean: 0.6700
      tp_score_std: 0.1900
      tp_data_ucls_mean: 0.0190
      tp_data_ucls_std: 0.0110
      tp_model_ucls_mean: 0.7932
      tp_model_ucls_std: 0.1906
      data_ureg_mean: 1.3505
      data_ureg_std: 0.2918
      model_ureg_mean: 0.0320
      model_ureg_std: 0.0146

    matcher:
      ego_mask: fasle

      # dataset: *dataset
      score_reliable: 0.6700
      u_cls_data_reliable: 0.7781
      u_cls_model_reliable: 0.8038
      u_reg_data_reliable: -0.1783
      u_reg_model_reliable: -0.1566

loss:
  core_method: point_pillar_tc_loss
  args:
    cls_weight: 1.0
    reg: 2.0
    # backbone_fix: True # 这个一旦固定就会去算flow estimate的损失

    dir_args: 
      dir_weight: 0.2
      args: *dir_args
      anchor_yaw: *anchor_yaw

optimizer:
  core_method: AdamW
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

  # core_method: Adam
  # lr: 0.002
  # args:
  #   eps: 1e-10
  #   weight_decay: 1e-4

  # core_method: Ranger21
  # lr: 0.0005
  # args:
  #   eps: 1e-10
  #   weight_decay: 1e-3
  #   # num_epochs: *epoches


lr_scheduler:
  # core_method: cosineannealwarm # step, multistep, exponential and cosineannealwarm support
  # epoches: *epoches
  # warmup_lr: 2e-5
  # warmup_epoches: 10
  # lr_min: 5e-6

  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 20, 35]

  # core_method: cosineannealinglr #step, multistep and Exponential support
  # T_max: 20
  # eta_min: 2e-5

  # core_method: ExponentialLR #step, multistep and Exponential support
  # gamma: 0.9



