# learnable flow
name: where2comm_flow_debug

root_dir: "/remote-home/share/OPV2V_irregular_npy/train"
validate_dir: "/remote-home/share/OPV2V_irregular_npy/validate"
test_dir: "/remote-home/share/OPV2V_irregular_npy/test"

noise_setting:
  add_noise: False
  # args: 
  #   pos_std: 0.2
  #   rot_std: 0.2
  #   pos_mean: 0
  #   rot_mean: 0

exp_name: ""
num_sweep_frames: &past_k 3

binomial_n: 10
binomial_p: 0.3
is_no_shift: true
is_same_sample_interval: false

is_single_pre_trained:
  pre_train_flag: false
  # pre_train_fix: false
  # pre_train_path: '/GPFS/rhome/yifanlu/workspace/OpenCOODv2/opencood/logs/point_pillar_late_fusion_channel256_2022_12_14_21_52_25'
  # pre_train_epoch: 24

comm_range: 200

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 1 # TODO: 调整batch_size
  epoches: 30
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 5
  supervise_single_flag: true

fusion:
  core_method: 'IntermediateFusionDatasetIrregular' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset, IntermediateFusionDatasetMultisweep supported
  args:
    proj_first: false
    clip_pc: false

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  past_k: *past_k
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav. Format: xyzxyz minmax
  cav_lidar_range: &cav_lidar [-140.8, -40, -3, 140.8, 40, 1] # [-140.8, -40, -3, 140.8, 40, 1] / [-153.6, -51.2, -3, 153.6, 51.2, 1], [-140.8, -38.4, -3, 140.8, 38.4, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 2
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: point_pillar_where2comm_flow
  
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: True
    num_sweep_frames: *past_k

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      resnet: true
      layer_nums: &layer_nums [3, 4, 5]
      layer_strides: [2, 2, 2]
      num_filters: &num_filters [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0
      voxel_size: *voxel_size
      
    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3
    
    # dcn:
    #   in_channels: [384]
    #   out_channels: [256]
    #   stride: [1]
    #   padding: [1]
    #   kernel_size : [3]
    #   n_blocks: 1

    rain_model:
      # d_ff: 256
      # h: 8
      # num_layers: 1
      # neighbor_range: 2
      # dropout: 0
      # max_len: 300
      # input_dim: 64
      voxel_size: *voxel_size
      downsample_rate: 1
      in_channels: 256
      channel_size: 256
      n_head: 8
      dropout_rate: 0
      only_attention: true
      # fusion_setting:
      #   sweep_length: *past_k
      #   if_spatial_encoding : False
      #   if_ego_time_encoding : false
      #   if_nonego_time_encoding : true
      #   if_sensor_encoding : False
      #   if_time_attn_aggre : true
      #   if_spatial_conv : False
      #   if_dotproductattn : True
      #   use_mask : True
      #   confidence_fetch : false
      communication:
        num_blocks_thres: 1  # 有效地块占总地块的比例最高值 [0, 1]
        round: 1
        thre: 0.01
        gaussian_smooth:
          k_size: 5
          c_sigma: 1.0
      agg_operator:
        mode: 'MAX' # MAX or RAIN
        feature_dim: 256
      multi_scale: True
      layer_nums: *layer_nums
      num_filters: *num_filters

loss:
  core_method: point_pillar_tc_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 20]

